### PR TITLE
Added more json data for builds and formatted some json files

### PR DESCRIPTION
**Pull request by Kira272921**

### CODE REVIEW

**Comment by StoneMcYT** [comment]
[Review dis PR](https://trello.com/c/pvQtgrqN/6-review-dis-pr)

**Review by StoneMcYT — APPROVED** [review]
Approved! Amazing formatting

**Comment by Kira272921** [comment]
> Approved! Amazing formatting

kek it was just one little click

**Comment by tintinkung** [comment]
btw formatting is cool but maybe keep the compress file? cus its _abit_ faster and _efficient_ in code.
like `locations.json `and `locations.min.json`

**Comment by Kira272921** [comment]
oh yesz, didn't think about that

**Comment by Kira272921** [comment]
@tintinkung chemck now

**Review by tintinkung — APPROVED** [review]
uwu

**Pull request merged**
